### ISSUE TITLE
Improve path handling

### ISSUE THREAD

**Issue by kirilklein** [FGA-DIKU/ehr2meds#3]
#### **Current Problem**
We need a clean way of handling input directories without specifying the full path for each concept.

---

### ✅ **Proposed Solution**
Introduce a **directory-based resolution system** where each file can reference its corresponding directory from a centralized `paths` configuration. This allows for:
- **Simplified file referencing** (no need for full paths).
- **More maintainable configuration** (easier updates to input locations).
- **Better separation of concerns** between general path settings and individual file mappings.

---

### 📂 **Updated Configuration Approach**
Instead of specifying full paths, we define input and output directories **once**:

#### **Define Paths in `paths.yaml`**
```yaml
paths:
  ##### Input Directories #########
  register: /path/to/register/
  sp: /path/to/sp/
  mapping: /path/to/mapping/

  ##### Output Directories #########
  output: /path/to/output/
```

#### **Specify Concepts Using Directories**
Each concept can now reference a **directory name** instead of hardcoding paths:

```yaml
concepts:
  admissions:
    directory: sp  # Refers to paths.sp
    filename: CPMI_ADTHaendelser.parquet  # File name within the directory
    columns_map:
      CPR_hash: subject_id
      Flyt_ind: admission
```

---

### 🔍 **Implementation Steps**
1. **Modify the file resolution logic**:
   - Instead of requiring full paths, resolve each file’s location dynamically using directory as a key to access the corresponding path 

3. **Update relevant modules**:
   - Modify **data loading logic** in `data_handler.py` to use this new structure.
   - Ensure **all file-related operations** respect the new directory-based resolution.
